updated french translation
thebigsmileXD/MagicWE2 pull request #144
Opened 2019-10-06 13:07 UTC by SergiyGolov

2019-10-06 14:20 UTC, inxomnyaa requested changes

2019-10-06 14:20 UTC, thebigsmileXD commented on resources/lang/fre.ini
>  noperm = "Vous n'avez pas la permission d'exécuter cette commande"
Please make sure to remove entries that are not present in https://github.com/thebigsmileXD/MagicWE2/blob/translations/resources/lang/eng.ini

2019-10-06 21:17 UTC, Toinane reviewed
I found some mistakes to correct. I corrected them in my comments

2019-10-06 21:17 UTC, Toinane commented on resources/lang/fre.ini
> +error.nosession = "Aucune session s'est crée - vous n'avez probablement pas le droit d'utiliser {%0}"
```suggestion
error.nosession = "Aucune session n'a été créée - vous n'avez probablement pas le droit d'utiliser {%0}"
```

2019-10-06 21:17 UTC, Toinane commented on resources/lang/fre.ini
> +error.command-error = "Il semble qu'il manque un argument ou que vous avez mal utilisé la commande!"
```suggestion
error.command-error = "Il semble qu'il manque un argument ou que vous ayez mal utilisé la commande !"
```

2019-10-06 21:17 UTC, Toinane commented on resources/lang/fre.ini
> +error.runingame = "Veuillez éxécuter cette commande en jeu!"
```suggestion
error.runingame = "Veuillez éxécuter cette commande en jeu !"
```

2019-10-06 21:17 UTC, Toinane commented on resources/lang/fre.ini
> +error.selectioninvalid = "Sélection non valide ! Vérifiez que toutes les positions sont définis"
```suggestion
error.selectioninvalid = "Sélection non valide ! Vérifiez que toutes les positions sont définies"
```

2019-10-06 21:17 UTC, Toinane commented on resources/lang/fre.ini
> +tool.wand.setenabled = "L'outil de vaguette est maintenant {%0}!"
```suggestion
tool.wand.setenabled = "L'outil de baguette est maintenant {%0}!"
```

2019-10-06 21:38 UTC, Toinane approved these changes
As I'm french, these translations seems to be good for me!

2019-10-07 12:36 UTC, inxomnyaa approved these changes

2019-10-07 12:37 UTC, thebigsmileXD commented
Thanks! 💯

2019-12-22 05:48 UTC, merged